base:
  project: youtube_comment_analysis
  random_state: 42

data_collection:
  datasets:
    primary: "vijayj0shi/reddit-dataset-with-sentiment-analysis"
    twitter_sentiment: "jp797498e/twitter-entity-sentiment-analysis"
    twitter_reddit_combined: "cosmos98/twitter-and-reddit-sentimental-analysis-dataset"

columns:
  text_raw: "Body"
  text_processed: "text_processed"
  target: "sentiment"
  numeric_features:
    - "char_count"
    - "word_count"
    - "avg_word_len"

preprocessing:
  train_test_split: 0.2
  drop_columns:
    - "Post_ID"
    - "Post_Title"
    - "Comment_ID"
    - "Parent_ID"
    - "Author"
    - "Confidence"
    - "Sentiment_Score"
  rename_columns:
    Score: upvotes

features:
  tfidf:
    max_features: 2500
    ngram_range: [1, 1]
  scaling: robust

train:
  model_name: lightgbm
  params:
    n_estimators: 1000
    learning_rate: 0.03
    num_leaves: 70
    max_depth: 10
    min_child_samples: 25
    subsample: 0.8
    colsample_bytree: 0.5
    reg_alpha: 0.5
    reg_lambda: 0.5
    min_split_gain: 0.7
    random_state: 42
    n_jobs: -1
